name: Release Docker image

on:
  push:
    # Only run on pushes to branches like "v1.2.3"
    branches:
      - 'v*.*.*'

jobs:
  release:
    # Skip branch-creation (first-commit) events
    if: ${{ github.event.before != '0000000000000000000000000000000000000000' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU (for Buildx)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version from branch
        run: echo "VERSION=${GITHUB_REF#refs/heads/v}" >> $GITHUB_ENV

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            razor29/flowrunner-cli:${{ env.VERSION }}
            razor29/flowrunner-cli:latest
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}
            org.opencontainers.image.description="Release ${{ env.VERSION }}"
